"""relations_event_location_resource_created

Revision ID: 07db183469ec
Revises: fb10173c7d97
Create Date: 2022-12-21 19:49:49.828402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07db183469ec'
down_revision = 'fb10173c7d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event', 'location', ['location_id'], ['id'], ondelete='CASCADE')
    op.add_column('resource', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'resource', 'event', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resource', type_='foreignkey')
    op.drop_column('resource', 'event_id')
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'location_id')
    # ### end Alembic commands ###
